apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-controller
  template:
    metadata:
      labels:
        app: agent-controller
    spec:
      containers:
      - name: agent-controller
        image: franczar/k8s-attestation-agent-controller:latest
