apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-deployer
  template:
    metadata:
      labels:
        app: agent-deployer
    spec:
      containers:
      - name: agent-deployer
        image: franczar/k8s-attestation-agent-deployer:latest
