apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.60.11
nodeRegistration:
  kubeletExtraArgs:
    node-labels: "node-role.kubernetes.io/master="
postKubeadmCommands:
- kubectl label nodes master node-role.kubernetes.io/control-plane=true --overwrite
- kubectl taint nodes --all node-role.kubernetes.io/control-plane-
- kubectl apply -f agent-deployer.yaml
- kubectl apply -f agent-controller.yaml
- kubectl apply -f pod-watcher.yaml
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  certSANs:
  - "192.168.60.11"
  - "example.com"
controlPlaneEndpoint: "192.168.60.11:6443"
networking:
  podSubnet: "192.168.0.0/16"
uploadCerts: true
