apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-watcher
  template:
    metadata:
      labels:
        app: pod-watcher
    spec:
      containers:
      - name: pod-watcher
        image: franczar/k8s-attestation-pod-watcher:latest
