apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
  namespace: attestation-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-watcher
  template:
    metadata:
      labels:
        app: pod-watcher
    spec:
      containers:
        - name: pod-watcher
          image: franczar/k8s-attestation-pod-watcher:latest
          volumeMounts:
            - name: kube-config
          mountPath: /root/.kube
      volumes:
        - name: kube-config
          hostPath:
            path: /home/node/.kube
