apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-handler
  template:
    metadata:
      labels:
        app: pod-handler
    spec:
      containers:
        - name: pod-handler
          image: franczar/k8s-attestation-pod-handler:latest
          env:
            - name: REGISTRAR_HOST
              value: "192.168.60.21"
            - name: REGISTRAR_PORT
              value: "30000"
            - name: POD_HANDLER_PORT
              value: "8081"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: kube-config
              mountPath: /root/.kube
      volumes:
        - name: kube-config
          hostPath:
            path: /home/node/.kube
---
apiVersion: v1
kind: Service
metadata:
  name: pod-handler-service
spec:
  selector:
    app: pod-handler
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort
